name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run check

      - name: Code smells
        run: npm run smells

      - name: Test
        run: npm run test:coverage

      - name: Build
        run: npm run build
